steps:
  # 1. Build da imagem Docker
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'europe-west1-docker.pkg.dev/$PROJECT_ID/gestnow-app/gestnow-v3', '.']

  # 2. Push da imagem para o Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'europe-west1-docker.pkg.dev/$PROJECT_ID/gestnow-app/gestnow-v3']

  # 3. Deploy para o Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'gestnow-v3'
      - '--image'
      - 'europe-west1-docker.pkg.dev/$PROJECT_ID/gestnow-app/gestnow-v3'
      - '--region'
      - 'europe-west1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '2'
      - '--timeout'
      - '3600'
      - '--set-env-vars'
      - 'GCS_BUCKET=gestnow-dados'
      - '--cpu-boost'

options:
  logging: CLOUD_LOGGING_ONLY
  default_logs_bucket_behavior: REGIONAL_USER_OWNED_BUCKET

images:
  - 'europe-west1-docker.pkg.dev/$PROJECT_ID/gestnow-app/gestnow-v3'
